
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 16 23:40:26 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 11;
  public static final int CHAR = 43;
  public static final int CONST = 15;
  public static final int GE = 40;
  public static final int LPAREN = 8;
  public static final int SEMI = 5;
  public static final int CONTINUE = 22;
  public static final int MINUS = 27;
  public static final int RPAREN = 9;
  public static final int AND = 34;
  public static final int LT = 37;
  public static final int OR = 33;
  public static final int COMMA = 10;
  public static final int INC = 31;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int IF = 17;
  public static final int LE = 38;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int RBRACKET = 12;
  public static final int EQUAL = 24;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 41;
  public static final int MOD = 30;
  public static final int IDENT = 44;
  public static final int BOOLVALUE = 42;
  public static final int BREAK = 21;
  public static final int VOID = 16;
  public static final int EQ = 35;
  public static final int COLON = 6;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int READ = 14;
  public static final int QUEST = 7;
  public static final int WHILE = 20;
  public static final int RBRACE = 4;
  public static final int NE = 36;
  public static final int PROG = 2;
  public static final int DEC = 32;
  public static final int GT = 39;
  public static final int PRINT = 13;
  public static final int DO = 19;
}

