
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 15 00:24:18 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 11;
  public static final int CHAR = 41;
  public static final int GE = 38;
  public static final int LPAREN = 8;
  public static final int SEMI = 5;
  public static final int CONTINUE = 21;
  public static final int MINUS = 25;
  public static final int RPAREN = 9;
  public static final int AND = 32;
  public static final int LT = 35;
  public static final int OR = 31;
  public static final int BOOL = 40;
  public static final int COMMA = 10;
  public static final int INC = 29;
  public static final int DIV = 27;
  public static final int PLUS = 24;
  public static final int IF = 16;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int RBRACKET = 12;
  public static final int EQUAL = 22;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 39;
  public static final int MOD = 28;
  public static final int IDENT = 42;
  public static final int BREAK = 20;
  public static final int VOID = 15;
  public static final int EQ = 33;
  public static final int COLON = 6;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int READ = 14;
  public static final int QUEST = 7;
  public static final int WHILE = 19;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int NE = 34;
  public static final int DEC = 30;
  public static final int GT = 37;
  public static final int PRINT = 13;
  public static final int DO = 18;
}

